theme: jekyll-theme-architect

title: PyGran
description: Python toolkit for DEM simulation & analysis
logo: images/logo.png
show_downloads: ["true"]
google_analytics: [UA-110372297-1]


footer-links:
  dribbble:
  email: andrew.gaam@gmail.com
  facebook:
  flickr:
  github: http://github.com/Andrew-AbiMansour
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
